=begin
DCIDDP

The Decentralised Identity Dispatch Protocol (DCIDDP) is a protocol that allows for dispension  of name and pronoun information in a decentralised manner, for rendering in a user interface.  The protocol is designed to be simple, lightweight, and easy to implement. 

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end

class InitTables < ActiveRecord::Migration
  def change
    create_table "error".pluralize.to_sym, id: false do |t|
      t.integer :code
      t.string :error

      t.timestamps
    end

    create_table "fronter".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name
      t.string :pronouns

      t.timestamps
    end

    create_table "member".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :pronouns
      t.string :id

      t.timestamps
    end

    create_table "partial_member".pluralize.to_sym, id: false do |t|
      t.string :name
      t.string :pronouns

      t.timestamps
    end

    create_table "partial_system".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name

      t.timestamps
    end

    create_table "pronoun".pluralize.to_sym, id: false do |t|
      t.string :subject
      t.string :object
      t.string :possessive
      t.string :possessive_determiner
      t.string :reflexive

      t.timestamps
    end

    create_table "system".pluralize.to_sym, id: false do |t|
      t.string :id
      t.string :name
      t.string :pronouns
      t.string :fronters
      t.string :members

      t.timestamps
    end

  end
end
