from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class Error(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, code=None, error=None):  # noqa: E501
        """Error - a model defined in OpenAPI

        :param code: The code of this Error.  # noqa: E501
        :type code: int
        :param error: The error of this Error.  # noqa: E501
        :type error: str
        """
        self.openapi_types = {
            'code': int,
            'error': str
        }

        self.attribute_map = {
            'code': 'code',
            'error': 'error'
        }

        self._code = code
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'Error':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The error of this Error.  # noqa: E501
        :rtype: Error
        """
        return util.deserialize_model(dikt, cls)

    @property
    def code(self) -> int:
        """Gets the code of this Error.

        The error code  # noqa: E501

        :return: The code of this Error.
        :rtype: int
        """
        return self._code

    @code.setter
    def code(self, code: int):
        """Sets the code of this Error.

        The error code  # noqa: E501

        :param code: The code of this Error.
        :type code: int
        """

        self._code = code

    @property
    def error(self) -> str:
        """Gets the error of this Error.

        The error message  # noqa: E501

        :return: The error of this Error.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this Error.

        The error message  # noqa: E501

        :param error: The error of this Error.
        :type error: str
        """

        self._error = error
