from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.pronoun import Pronoun
from openapi_server import util

from openapi_server.models.pronoun import Pronoun  # noqa: E501

class Fronter(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, pronouns=None):  # noqa: E501
        """Fronter - a model defined in OpenAPI

        :param id: The id of this Fronter.  # noqa: E501
        :type id: str
        :param name: The name of this Fronter.  # noqa: E501
        :type name: str
        :param pronouns: The pronouns of this Fronter.  # noqa: E501
        :type pronouns: List[Pronoun]
        """
        self.openapi_types = {
            'id': str,
            'name': str,
            'pronouns': List[Pronoun]
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'pronouns': 'pronouns'
        }

        self._id = id
        self._name = name
        self._pronouns = pronouns

    @classmethod
    def from_dict(cls, dikt) -> 'Fronter':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The fronter of this Fronter.  # noqa: E501
        :rtype: Fronter
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Fronter.

        The ID of the fronter  # noqa: E501

        :return: The id of this Fronter.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Fronter.

        The ID of the fronter  # noqa: E501

        :param id: The id of this Fronter.
        :type id: str
        """

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Fronter.

        The name of the fronter  # noqa: E501

        :return: The name of this Fronter.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Fronter.

        The name of the fronter  # noqa: E501

        :param name: The name of this Fronter.
        :type name: str
        """

        self._name = name

    @property
    def pronouns(self) -> List[Pronoun]:
        """Gets the pronouns of this Fronter.


        :return: The pronouns of this Fronter.
        :rtype: List[Pronoun]
        """
        return self._pronouns

    @pronouns.setter
    def pronouns(self, pronouns: List[Pronoun]):
        """Sets the pronouns of this Fronter.


        :param pronouns: The pronouns of this Fronter.
        :type pronouns: List[Pronoun]
        """

        self._pronouns = pronouns
