from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.pronoun import Pronoun
from openapi_server import util

from openapi_server.models.pronoun import Pronoun  # noqa: E501

class Member(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, name=None, pronouns=None, id=None):  # noqa: E501
        """Member - a model defined in OpenAPI

        :param name: The name of this Member.  # noqa: E501
        :type name: str
        :param pronouns: The pronouns of this Member.  # noqa: E501
        :type pronouns: List[Pronoun]
        :param id: The id of this Member.  # noqa: E501
        :type id: str
        """
        self.openapi_types = {
            'name': str,
            'pronouns': List[Pronoun],
            'id': str
        }

        self.attribute_map = {
            'name': 'name',
            'pronouns': 'pronouns',
            'id': 'id'
        }

        self._name = name
        self._pronouns = pronouns
        self._id = id

    @classmethod
    def from_dict(cls, dikt) -> 'Member':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The member of this Member.  # noqa: E501
        :rtype: Member
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Member.

        The name of the member  # noqa: E501

        :return: The name of this Member.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Member.

        The name of the member  # noqa: E501

        :param name: The name of this Member.
        :type name: str
        """

        self._name = name

    @property
    def pronouns(self) -> List[Pronoun]:
        """Gets the pronouns of this Member.


        :return: The pronouns of this Member.
        :rtype: List[Pronoun]
        """
        return self._pronouns

    @pronouns.setter
    def pronouns(self, pronouns: List[Pronoun]):
        """Sets the pronouns of this Member.


        :param pronouns: The pronouns of this Member.
        :type pronouns: List[Pronoun]
        """

        self._pronouns = pronouns

    @property
    def id(self) -> str:
        """Gets the id of this Member.

        The ID of the member  # noqa: E501

        :return: The id of this Member.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Member.

        The ID of the member  # noqa: E501

        :param id: The id of this Member.
        :type id: str
        """

        self._id = id
