=begin
DCIDDP

The Decentralised Identity Dispatch Protocol (DCIDDP) is a protocol that allows for dispension  of name and pronoun information in a decentralised manner, for rendering in a user interface.  The protocol is designed to be simple, lightweight, and easy to implement. 

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
class DefaultController < ApplicationController

  def system_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def system_system_fronters_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def system_system_fronters_put
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def system_system_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def system_system_member_member_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def system_system_member_member_pronouns_get
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def system_system_members_post
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
