/*
 * DCIDDP
 *
 * The Decentralised Identity Dispatch Protocol (DCIDDP) is a protocol that allows for dispension  of name and pronoun information in a decentralised manner, for rendering in a user interface.  The protocol is designed to be simple, lightweight, and easy to implement. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DefaultAPIService is a service that implements the logic for the DefaultAPIServicer
// This service should implement the business logic for every endpoint for the DefaultAPI API.
// Include any external packages or services that will be required by this service.
type DefaultAPIService struct {
}

// NewDefaultAPIService creates a default api service
func NewDefaultAPIService() DefaultAPIServicer {
	return &DefaultAPIService{}
}

// SystemPost - Create a new plural system
func (s *DefaultAPIService) SystemPost(ctx context.Context, partialSystem PartialSystem) (ImplResponse, error) {
	// TODO - update SystemPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, System{}) or use other options such as http.Ok ...
	// return Response(201, System{}), nil

	// TODO: Uncomment the next line to return response Response(401, ModelError{}) or use other options such as http.Ok ...
	// return Response(401, ModelError{}), nil

	// TODO: Uncomment the next line to return response Response(400, ModelError{}) or use other options such as http.Ok ...
	// return Response(400, ModelError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SystemPost method not implemented")
}

// SystemSystemFrontersGet - Retrieves the current fronters&#39; API paths
func (s *DefaultAPIService) SystemSystemFrontersGet(ctx context.Context, system string) (ImplResponse, error) {
	// TODO - update SystemSystemFrontersGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Fronter{}) or use other options such as http.Ok ...
	// return Response(200, []Fronter{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SystemSystemFrontersGet method not implemented")
}

// SystemSystemFrontersPut - Set the fronter of a plural system
func (s *DefaultAPIService) SystemSystemFrontersPut(ctx context.Context, system string, requestBody []string) (ImplResponse, error) {
	// TODO - update SystemSystemFrontersPut with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, {}) or use other options such as http.Ok ...
	// return Response(200, nil),nil

	// TODO: Uncomment the next line to return response Response(400, ModelError{}) or use other options such as http.Ok ...
	// return Response(400, ModelError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SystemSystemFrontersPut method not implemented")
}

// SystemSystemGet - Get plural system information
func (s *DefaultAPIService) SystemSystemGet(ctx context.Context, system string) (ImplResponse, error) {
	// TODO - update SystemSystemGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, System{}) or use other options such as http.Ok ...
	// return Response(200, System{}), nil

	// TODO: Uncomment the next line to return response Response(404, ModelError{}) or use other options such as http.Ok ...
	// return Response(404, ModelError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SystemSystemGet method not implemented")
}

// SystemSystemMemberMemberGet - Get member information
func (s *DefaultAPIService) SystemSystemMemberMemberGet(ctx context.Context, system string, member string) (ImplResponse, error) {
	// TODO - update SystemSystemMemberMemberGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, Member{}) or use other options such as http.Ok ...
	// return Response(200, Member{}), nil

	// TODO: Uncomment the next line to return response Response(404, ModelError{}) or use other options such as http.Ok ...
	// return Response(404, ModelError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SystemSystemMemberMemberGet method not implemented")
}

// SystemSystemMemberMemberPronounsGet - Get member pronouns
func (s *DefaultAPIService) SystemSystemMemberMemberPronounsGet(ctx context.Context, system string, member string) (ImplResponse, error) {
	// TODO - update SystemSystemMemberMemberPronounsGet with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, []Pronoun{}) or use other options such as http.Ok ...
	// return Response(200, []Pronoun{}), nil

	// TODO: Uncomment the next line to return response Response(404, ModelError{}) or use other options such as http.Ok ...
	// return Response(404, ModelError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SystemSystemMemberMemberPronounsGet method not implemented")
}

// SystemSystemMembersPost - Add a new member to a plural system
func (s *DefaultAPIService) SystemSystemMembersPost(ctx context.Context, system string, partialMember PartialMember) (ImplResponse, error) {
	// TODO - update SystemSystemMembersPost with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(201, Member{}) or use other options such as http.Ok ...
	// return Response(201, Member{}), nil

	// TODO: Uncomment the next line to return response Response(401, ModelError{}) or use other options such as http.Ok ...
	// return Response(401, ModelError{}), nil

	// TODO: Uncomment the next line to return response Response(403, ModelError{}) or use other options such as http.Ok ...
	// return Response(403, ModelError{}), nil

	// TODO: Uncomment the next line to return response Response(400, ModelError{}) or use other options such as http.Ok ...
	// return Response(400, ModelError{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("SystemSystemMembersPost method not implemented")
}
