/*
 * DCIDDP
 *
 * The Decentralised Identity Dispatch Protocol (DCIDDP) is a protocol that allows for dispension  of name and pronoun information in a decentralised manner, for rendering in a user interface.  The protocol is designed to be simple, lightweight, and easy to implement. 
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi




type Pronoun struct {

	// The subject pronoun
	Subject string `json:"subject,omitempty"`

	// The object pronoun
	Object string `json:"object,omitempty"`

	// The possessive pronoun
	Possessive string `json:"possessive,omitempty"`

	// The possessive determiner
	PossessiveDeterminer string `json:"possessive_determiner,omitempty"`

	// The reflexive pronoun
	Reflexive string `json:"reflexive,omitempty"`
}

// AssertPronounRequired checks if the required fields are not zero-ed
func AssertPronounRequired(obj Pronoun) error {
	return nil
}

// AssertPronounConstraints checks if the values respects the defined constraints
func AssertPronounConstraints(obj Pronoun) error {
	return nil
}
