/*
DCIDDP

The Decentralised Identity Dispatch Protocol (DCIDDP) is a protocol that allows for dispension  of name and pronoun information in a decentralised manner, for rendering in a user interface.  The protocol is designed to be simple, lightweight, and easy to implement. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the Fronter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Fronter{}

// Fronter struct for Fronter
type Fronter struct {
	// The ID of the fronter
	Id *string `json:"id,omitempty"`
	// The name of the fronter
	Name *string `json:"name,omitempty"`
	Pronouns []Pronoun `json:"pronouns,omitempty"`
}

// NewFronter instantiates a new Fronter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFronter() *Fronter {
	this := Fronter{}
	return &this
}

// NewFronterWithDefaults instantiates a new Fronter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFronterWithDefaults() *Fronter {
	this := Fronter{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *Fronter) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fronter) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *Fronter) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *Fronter) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *Fronter) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fronter) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *Fronter) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *Fronter) SetName(v string) {
	o.Name = &v
}

// GetPronouns returns the Pronouns field value if set, zero value otherwise.
func (o *Fronter) GetPronouns() []Pronoun {
	if o == nil || IsNil(o.Pronouns) {
		var ret []Pronoun
		return ret
	}
	return o.Pronouns
}

// GetPronounsOk returns a tuple with the Pronouns field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Fronter) GetPronounsOk() ([]Pronoun, bool) {
	if o == nil || IsNil(o.Pronouns) {
		return nil, false
	}
	return o.Pronouns, true
}

// HasPronouns returns a boolean if a field has been set.
func (o *Fronter) HasPronouns() bool {
	if o != nil && !IsNil(o.Pronouns) {
		return true
	}

	return false
}

// SetPronouns gets a reference to the given []Pronoun and assigns it to the Pronouns field.
func (o *Fronter) SetPronouns(v []Pronoun) {
	o.Pronouns = v
}

func (o Fronter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Fronter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Pronouns) {
		toSerialize["pronouns"] = o.Pronouns
	}
	return toSerialize, nil
}

type NullableFronter struct {
	value *Fronter
	isSet bool
}

func (v NullableFronter) Get() *Fronter {
	return v.value
}

func (v *NullableFronter) Set(val *Fronter) {
	v.value = val
	v.isSet = true
}

func (v NullableFronter) IsSet() bool {
	return v.isSet
}

func (v *NullableFronter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFronter(val *Fronter) *NullableFronter {
	return &NullableFronter{value: val, isSet: true}
}

func (v NullableFronter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFronter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


