=begin
DCIDDP

The Decentralised Identity Dispatch Protocol (DCIDDP) is a protocol that allows for dispension  of name and pronoun information in a decentralised manner, for rendering in a user interface.  The protocol is designed to be simple, lightweight, and easy to implement. 

The version of the OpenAPI document: 1.0.0
Generated by: https://github.com/openapitools/openapi-generator.git

=end
Rails.application.routes.draw do

  def add_openapi_route http_method, path, opts = {}
    full_path = path.gsub(/{(.*?)}/, ':\1')
    match full_path, to: "#{opts.fetch(:controller_name)}##{opts[:action_name]}", via: http_method
  end

  add_openapi_route 'POST', '/system', controller_name: 'default', action_name: 'system_post'
  add_openapi_route 'GET', '/system/{system}/fronters', controller_name: 'default', action_name: 'system_system_fronters_get'
  add_openapi_route 'PUT', '/system/{system}/fronters', controller_name: 'default', action_name: 'system_system_fronters_put'
  add_openapi_route 'GET', '/system/{system}', controller_name: 'default', action_name: 'system_system_get'
  add_openapi_route 'GET', '/system/{system}/member/{member}', controller_name: 'default', action_name: 'system_system_member_member_get'
  add_openapi_route 'GET', '/system/{system}/member/{member}/pronouns', controller_name: 'default', action_name: 'system_system_member_member_pronouns_get'
  add_openapi_route 'POST', '/system/{system}/members', controller_name: 'default', action_name: 'system_system_members_post'
end
